apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  creationTimestamp: null
  name: app-qa1
  namespace: qa1
spec:
  components:
  - name: app-qa1-web-web
    properties:
      addRevisionLabel: false
      cpu: "0.1"
      exposeType: ClusterIP
      image: nginx
      imagePullPolicy: IfNotPresent
      memory: 20Mi
      ports:
      - expose: true
        port: 80
        protocol: TCP
    type: webservice
  policies:
  - name: topology-clusters
    properties:
      clusters:
      - eks
    type: topology
  workflow:
    steps:
    - name: deploy
      properties:
        ignoreTerraformComponent: false
        policies:
        - topology-clusters
      type: deploy
status: {}
