apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    application.deploy.reform/commitHash: d74332383566e8f2dc37b165541e6abb36b0c7f9
    application.deploy.reform/deploymentNo: app-qa1-DP1
    application.deploy.reform/name: app-qa1
    application.deploy.reform/revision: 2023.03.1
    deploy.reform/domain: reslv.io
    deploy.reform/version: a463dd478a21f2dc41a8ad45a1a54019222c6b94
  creationTimestamp: null
  name: app-qa1
  namespace: qa1
spec:
  components:
  - name: app-qa1-web-web
    properties:
      addRevisionLabel: false
      cpu: "0.1"
      exposeType: ClusterIP
      image: nginx
      imagePullPolicy: IfNotPresent
      memory: 20Mi
      ports:
      - expose: true
        port: 80
        protocol: TCP
    type: webservice
  policies:
  - name: topology-clusters
    properties:
      clusters:
      - eks
    type: topology
  workflow:
    steps:
    - name: deploy
      properties:
        ignoreTerraformComponent: false
        policies:
        - topology-clusters
      type: deploy
status: {}
