apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  creationTimestamp: null
  name: s3-uat
  namespace: uat
spec:
  components:
  - name: s3-uat-s3-infrastructure
    properties:
      accesslevel: private
      credentialRef: aws-credentials
      name: s3-086894234
      ociPackageName: aws-package
      workspace: default
    type: wv-aws-s3
  policies:
  - name: topology-clusters
    properties:
      clusters:
      - local
    type: topology
  workflow:
    steps:
    - name: deploy
        policies:
        - topology-clusters
      type: deploy
status: {}
