apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    application.deploy.reform/commitHash: 67514a3afedd7e9c1436c888f09dedba9c5f1e74
    application.deploy.reform/deploymentNo: web-1-DP2
    application.deploy.reform/environment: uat
    application.deploy.reform/name: web-1
    application.deploy.reform/repository: https://github.com/kreslv/applications.git
    application.deploy.reform/repositoryPath: web-1
    application.deploy.reform/revision: 2023.03.2
    deploy.reform/domain: reslv.io
    deploy.reform/version: e032374119aa1b3541b2317a59a46715620086c9
  creationTimestamp: null
  name: web-1
  namespace: uat
spec:
  components:
  - name: web-1-web-web
    properties:
      addRevisionLabel: false
      cpu: "5"
      exposeType: ClusterIP
      image: nginx
      imagePullPolicy: IfNotPresent
      memory: 10Mi
      ports:
      - expose: true
        port: 80
        protocol: TCP
    type: webservice
  policies:
  - name: topology-clusters
    properties:
      clusters:
      - local
    type: topology
  workflow:
    steps:
    - name: deploy
      properties:
        ignoreTerraformComponent: false
        policies:
        - topology-clusters
      type: deploy
status: {}
