apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    application.deploy.reform/commitHash: 1a4da137558970f5c3cf71419d01860fda68d572
    application.deploy.reform/deploymentNo: s3-DP1
    application.deploy.reform/name: s3
    application.deploy.reform/revision: 2023.03.1
    deploy.reform/domain: reslv.io
    deploy.reform/version: a463dd478a21f2dc41a8ad45a1a54019222c6b94
  creationTimestamp: null
  name: s3
  namespace: uat
spec:
  components:
  - name: s3-s3-infrastructure
    properties:
      accesslevel: private
      credentialRef: aws
      name: s3-fdfstert
      ociPackageName: aws-package
      workspace: default
    type: wv-aws-s3
  policies:
  - name: topology-clusters
    properties:
      clusters:
      - local
    type: topology
  workflow:
    steps:
    - name: deploy
      properties:
        ignoreTerraformComponent: false
        policies:
        - topology-clusters
      type: deploy
status: {}
