apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    application.deploy.reform/commitHash: 3538e6d4eedda961311eef966e7281ffdd8273e9
    application.deploy.reform/deploymentNo: app2-qa1-DP2
    application.deploy.reform/environment: qa1
    application.deploy.reform/name: app2-qa1
    application.deploy.reform/repository: https://github.com/kreslv/applications.git
    application.deploy.reform/repositoryPath: app2-qa1
    application.deploy.reform/revision: 2023.03.2
    deploy.reform/domain: reslv.io
    deploy.reform/version: e032374119aa1b3541b2317a59a46715620086c9
  creationTimestamp: null
  name: app2-qa1
  namespace: qa1
spec:
  components:
  - name: app2-qa1-helm-k8s
    properties:
      chart: hello-world
      installTimeout: 10m
      interval: 30s
      pullInterval: 5m
      repoType: helm
      retries: 3
      url: https://helm.github.io/examples
      version: '*'
    type: helm
  policies:
  - name: topology-clusters
    properties:
      clusters:
      - eks
    type: topology
  workflow:
    steps:
    - name: deploy
      properties:
        ignoreTerraformComponent: false
        policies:
        - topology-clusters
      type: deploy
status: {}
