apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    application.deploy.reform/commitHash: 2455517d6508f4912541f4358ba10258e06880d3
    application.deploy.reform/deploymentNo: web-uat-DP4
    application.deploy.reform/name: web-uat
    application.deploy.reform/revision: 2023.03.4
    deploy.reform/domain: reslv.io
    deploy.reform/version: a463dd478a21f2dc41a8ad45a1a54019222c6b94
  creationTimestamp: null
  name: web-uat
  namespace: uat
spec:
  components:
  - dependsOn:
    - web-uat-s3-infrastructure
    name: web-uat-web-web
    properties:
      addRevisionLabel: false
      cpu: "0.1"
      exposeType: ClusterIP
      image: nginx
      imagePullPolicy: IfNotPresent
      memory: 20Mi
      ports:
      - expose: true
        port: 80
        protocol: TCP
    type: webservice
  - name: web-uat-s3-infrastructure
    properties:
      accesslevel: private
      credentialRef: aws-creationals
      name: s3-543656
      ociPackageName: aws-package
      workspace: default
    type: wv-aws-s3
  policies:
  - name: topology-clusters
    properties:
      clusters:
      - local
    type: topology
  workflow:
    steps:
    - name: deploy
      properties:
        ignoreTerraformComponent: false
        policies:
        - topology-clusters
      type: deploy
status: {}
