apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    application.deploy.reform/commitHash: 68b6671824743cd5fb8d92cd0828f5433ef3ed1c
    application.deploy.reform/deploymentNo: web-uat-DP1
    application.deploy.reform/name: web-uat
    application.deploy.reform/revision: 2023.03.1
    deploy.reform/domain: reslv.io
    deploy.reform/version: a463dd478a21f2dc41a8ad45a1a54019222c6b94
  creationTimestamp: null
  name: web-uat
  namespace: uat
spec:
  components:
  - name: web-uat-web-web
    properties:
      addRevisionLabel: false
      cpu: "0.1"
      exposeType: ClusterIP
      image: nginx
      imagePullPolicy: IfNotPresent
      memory: 20Mi
      ports:
      - expose: true
        port: 80
        protocol: TCP
    type: webservice
  policies:
  - name: topology-clusters
    properties:
      clusters:
      - local
    type: topology
  workflow:
    steps:
    - name: deploy
      properties:
        ignoreTerraformComponent: false
        policies:
        - topology-clusters
      type: deploy
status: {}
